### ISSUE TITLE
Less greater swap

### ISSUE THREAD

**Issue by maxim092001** [NelosG/fp-tests#31]
Кусочек [тестов](https://github.com/NelosG/fp-tests/blob/master/hw3/test/Hi/Test/T2Spec.hs#L87)

```haskell
      it "less greater swap" $ hedgehog $ do
      a <- forAll genExpr
      b <- forAll genExpr
      testSameEval
        (HiExprApply (funToExpr HiFunGreaterThan) ([a, b]))
        (HiExprApply (funToExpr HiFunLessThan) ([b, a]))
```

Если
a = add(1)
b = 1(1)

То ошибки будут различные

a < b выдаст нам HiErrorInvalidArity
b > a выдаст нам HiErrorInvalidFunction

a ---- HiExprApply (HiExprValue (HiValueFunction HiFunAdd)) [ HiExprValue (HiValueNumber (1 % 1)) ]
b ---- HiExprApply (HiExprValue (HiValueNumber (1 % 1))) [ HiExprValue (HiValueNumber (1 % 1)) ]

Лог ошибки:
               ┃ │ ━━━ Failed (- lhs) (+ rhs) ━━━
               ┃ │ - EvalError HiErrorArityMismatch
               ┃ │ + EvalError HiErrorInvalidFunction

**Comment by Jovvik** [comment]
Пофикшу через час
