### ISSUE TITLE
Operators on empty strings

### ISSUE THREAD

**Issue by maxim092001** [NelosG/fp-tests#43]
Проблема [тут](https://github.com/NelosG/fp-tests/blob/master/hw3/test/Hi/Test/T4Spec.hs#L62)

"" * 5 это пустая строка, а не null. null появляется только при out-of-bound

prove me wrong

**Comment by Jovvik** [comment]
Кажется, ты как-то не так понял ошибку, у меня `"" * 5` дает `""` и тесты проходят

**Comment by maxim092001** [comment]
дап, соре
