### ISSUE TITLE
Не проверяется умножение строчки на нецелое число.

### ISSUE THREAD

**Issue by kuchma19** [NelosG/fp-tests#49]

**Comment by maxim092001** [comment]
оно вроде implementation defined, не очень понятно как нам его чекать
Кто-то округляет, а кто-то кидает invalid

**Comment by kuchma19** [comment]
> оно вроде implementation defined, не очень понятно как нам его чекать Кто-то округляет, а кто-то кидает invalid

Был задан вот такой вопрос. И считаю, что умножение на нецелое число это HiErrorInvalidArgument.

![image](https://user-images.githubusercontent.com/60818968/148696527-9dc5b231-4684-4ff4-8926-9077b106a370.png)

**Comment by Jovvik** [comment]
Даже вот такой вопрос был

![image](https://user-images.githubusercontent.com/31628566/148697208-3df6e74f-4b16-4b60-80b4-14bcbda48d83.png)

**Comment by maxim092001** [comment]
> Даже вот такой вопрос был
> 
> ![image](https://user-images.githubusercontent.com/31628566/148697208-3df6e74f-4b16-4b60-80b4-14bcbda48d83.png)

а на это тесты есть

**Comment by maxim092001** [comment]
> > оно вроде implementation defined, не очень понятно как нам его чекать Кто-то округляет, а кто-то кидает invalid
> 
> Был задан вот такой вопрос. И считаю, что умножение на нецелое число это HiErrorInvalidArgument.
> 
> ![image](https://user-images.githubusercontent.com/60818968/148696527-9dc5b231-4684-4ff4-8926-9077b106a370.png)

соре, я продолбал
